### PR TITLE
Create _config.yml

### PR DESCRIPTION
**Pull request by simonv3**
Some basic settings copied from events. Todo with #4.

### CODE REVIEW

**Comment by equinusocio** [comment]
I can't test It, it works?

**Comment by simonv3** [comment]
@equinusocio I hadn't thoroughly tested it at first but just added a commit that more fully implements the website.

It would look like this:
screenshot 2016-10-10 09 03 42

Which is super minimal, but it creates the page.

To properly see if GitHub picks it up we'll have to merge it in I think. Jekyll doesn't complain.

**Comment by evalica** [comment]
It looks nice for a first version. 
My only comment is that since it's just a line, it could have like a centered alignment too :)

**Comment by simonv3** [comment]
Hmm, let me see if the main CSS has some styles I can steal for this.

**Comment by simonv3** [comment]
screenshot 2016-10-11 07 15 28

And centered!

**Comment by evalica** [comment]
I think it looks nice. Thanks @simonv3 
In the future we should provide a layout for the talks (in another issue) since we already have some talks + we can also list the talks from the FOSDEM room (we would need to find a way to display in a PDF viewer or embedded presentations).

**Comment by simonv3** [comment]
Yeah, this is definitely a first step. Just wanted to make sure the website actually existed!

**Comment by Erioldoesdesign** [comment]
I think we're merging this 'talks' repo with the main website repo. Would this change work on the site if this repo is deleted/merged?

**Comment by RDIL** [comment]
Closing as after the merge (https://github.com/opensourcedesign/opensourcedesign.github.io/issues/236 's part in this repository), it won't be needed.

**Pull request closed without merging**
